version: '3'

services:
  kb-fast:
    build: .  
    image: rubat0/kb-fast-app:latest
    ports:
      - "8000:8000"
    environment:
      SEARCH_DIRECTORY_PATH: '/app/KB/file'
      KOBART_MODEL_PATH: '/app/KB/ko-bart'
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
